
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 28 19:14:24 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int LV = 12;
  public static final int RV = 11;
  public static final int SIN = 20;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int COS = 21;
  public static final int SEMI = 2;
  public static final int LN = 19;
  public static final int MAG = 17;
  public static final int SQRT = 23;
  public static final int POW = 10;
  public static final int LPAREN = 7;
  public static final int ID = 26;
  public static final int COMA = 13;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int NORM = 16;
  public static final int DIVIDE = 6;
  public static final int VEC = 15;
  public static final int PI = 25;
  public static final int MINUS = 4;
  public static final int DOT = 18;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int TAN = 22;
  public static final int DOUBLE = 14;
}

